# This workflow uses actions that are not certified by GitHub. They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ] # Jos repositoriosi p채채haara ei ole main, muuta n채m채
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Configure Environment
        env:
          CHROMIUM_EXECUTABLE: /usr/bin/chromium-browser
        run: echo "CHROMIUM_EXECUTABLE=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Bundle Install
        run: bundle install

      - name: Run Tests with Headless Browser
        run: |
          export BROWSER=/usr/bin/chromium-browser # Set the headless browser for Capybara
          bundle exec rspec
